### ISSUE TITLE
Investigate slow compile times with new kfac-jax version

### ISSUE THREAD

**Issue by zenoone** [deepqmc/deepqmc#118]
_The new 0.0.5 release of kfac-jax results in extremely slow compile times. Until this is investigated, we use the previous 0.0.3 version of kfac-jax._ #117 

The slow compile times should be investigated, to lift the restriction to jax-kfac 0.0.3.

**Comment by szbernat** [comment]
Resolved, slower compile times were a result of some unrelated recent changes in the code.
