### ISSUE TITLE
Install on Apple Silicon chip

### ISSUE THREAD

**Issue by minhtriet** [deepqmc/deepqmc#148]
Is it possible to leverage the power of Apple Silicon chip when running DeepQMC. As far as I can tell it depends on JAX and JAX does support Apple Silicon https://developer.apple.com/metal/jax/

**Comment by szbernat** [comment]
DeepQMC is not tested on Apple Silicon, but in principle there is no reason why it shouldn't work. One would have to install the custom JAX version as described in the above link, and the install DeepQMC as usual.
