### ISSUE TITLE
Add more ansatzes

### ISSUE THREAD

**Issue by jhrmnn** [deepqmc/deepqmc#19]
- some standard Jastrow factor
- FermiNet

**Comment by CompRhys** [comment]
Re: deepchem/deepchem#1676: Having looked at the FermiNet code from DM and the PauliNet code here, There's definitely a lot of technical overlap but the engineering/structure of the codebases appears not to be hugely compatible which would make doing the transposition (tf2pytorch) a rather more involved process as it would require a fairly complete understanding of both codebases not just a good understanding of both frameworks.

**Comment by jhrmnn** [comment]
Thanks for the analysis. Probably not too surprising that this is the case. The core pieces that would need to be taken over seem to be:

- Large part of [`networks.py`](https://github.com/deepmind/ferminet/blob/27f90beb57de62333989a5a64f47d1759b33804e/ferminet/networks.py) with its `FermiNet` class.
- [`r12_features()`](https://github.com/deepmind/ferminet/blob/27f90beb57de62333989a5a64f47d1759b33804e/ferminet/hamiltonian.py#L127) from `hamiltonian.py`

The rest of the codebase doesn't seem to be ansatz-specific. Except for K-FAC (which is crucial for FermiNet, though), all the necessary QMC machinery should already be in DeepQMC.
