### ISSUE TITLE
Add K-FAC

### ISSUE THREAD

**Issue by jhrmnn** [deepqmc/deepqmc#20]

**Comment by n-gao** [comment]
As PyTorch does not have a default KFAC implementation, do you intend to implement your own KFAC? I do have a relatively general KFAC implementation available here: https://github.com/n-gao/pytorch-kfac which includes most of the important features of the tensorflow implementation.

**Comment by jhrmnn** [comment]
Yes. I actually already have a mostly working implementation, just not finalized enough to make it public.

But it would be definitely useful to be able to use multiple implementations, if only to be able to test correctness.

So I'd be happy to accept a PR that integrates your K-FAC package into deepqmc.
