### ISSUE TITLE
Error while following the tutorial with CPU and not GPU.

### ISSUE THREAD

**Issue by RicardoLopezDoria** [deepqmc/deepqmc#205]
Hi, I just installed deepQMC in WSL into a conda environment.
I get this error while running this:

```
from deepqmc import Molecule

# mol = Molecule.from_name('LiH')

print(Molecule.all_names)
```

error:
(deepQMC) (base) ricardol@amenadiel:~/deepQMC$ /home/ricardol/anaconda3/envs/deepQMC/bin/python /home/ricardol/deepQMC/tutorial.py
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
Traceback (most recent call last):
  File "/home/ricardol/deepQMC/tutorial.py", line 1, in <module>
    from deepqmc import Molecule
  File "/home/ricardol/anaconda3/envs/deepQMC/lib/python3.12/site-packages/deepqmc/__init__.py", line 33, in <module>
    from .train import train  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ricardol/anaconda3/envs/deepQMC/lib/python3.12/site-packages/deepqmc/train.py", line 12, in <module>
    from deepqmc.optimizer import construct_optimizer
  File "/home/ricardol/anaconda3/envs/deepQMC/lib/python3.12/site-packages/deepqmc/optimizer.py", line 7, in <module>
    from deepqmc.kfacext import batch_size_extractor, make_graph_patterns
  File "/home/ricardol/anaconda3/envs/deepQMC/lib/python3.12/site-packages/deepqmc/kfacext.py", line 6, in <module>
    from kfac_jax._src.utils import (
ImportError: cannot import name 'psd_inv_cholesky' from 'kfac_jax._src.utils' (/home/ricardol/anaconda3/envs/deepQMC/lib/python3.12/site-packages/kfac_jax/_src/utils/__init__.py)

![imagen](https://github.com/user-attachments/assets/420213ab-b479-4069-aeef-30784fa8942d)

I don't know what to do. Any ideas?

PS: I'm using Python 3.12.4

**Comment by zenoone** [comment]
Hi Ricardo,

Thanks for trying `deepqmc` and opening the issue.

You are experiencing problems due to conflicting versions of the `deepqmc` dependencies. We have updated the `pyproject.toml` with more restrictive versions, see #206.

Please try a fresh install with the latest version of `deepqmc`. You should be able to get a functional `deepqmc` with CPU support by running

    $ pip install -e .[dev]

For GPU support, upgrade `jax` to the GPU version with a matching `cuda` installation. For `cuda 12` this would be

    $ pip install --upgrade "jax[cuda12_pip]<0.4.24" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

Note the restriction to `jax 0.4.23` or lower.

We have found that installing `jax 0.4.23` may not enable GPU support on all machines due to issues with the `cudnn` library. A workaround is to downgrade to `nvidia-cudnn-cu12==8.9.7.29`

    $ pip install nvidia-cudnn-cu12==8.9.7.29

Please let us know if this solves your problem, and don't hesitate to create new issues if you have any other difficulties with running `deepqmc`.


I would also like to mention that we are working on a new major release of `deepqmc` which will allow the use of the latest versions of `jax`, `kfac-jax`, `numpy`, etc. and will have a lot of new exciting features.

**Comment by zenoone** [comment]
Good to hear that `deepqmc` is up and running. 

`deepqmc` relies on `jax` for GPU acceleration. While `jax` natively supports nvida-GPUs, according to the [documentation](https://jax.readthedocs.io/en/latest/installation.html#supported-platforms) it may be possible to install `jax` on AMD-GPUs, albeit this requires a [slightly more involved setup](https://jax.readthedocs.io/en/latest/installation.html#install-amd-gpu). Unfortunately we don't have access to AMD-GPUs to provide further details on the process. However, I can report that we have successfully build `jax` with intel-GPUs before.

**Comment by RicardoLopezDoria** [comment]
Hi, 

I'm still following the tutorial. I'm trying to do the calculations with the predefined LiH molecule. This is my code which I basically copied from the [tutorial](https://deepqmc.github.io/tutorial.html):

`import deepqmc
import os
import haiku as hk
from hydra import compose, initialize_config_dir
from hydra.utils import instantiate
from deepqmc.app import instantiate_ansatz
from deepqmc.wf import NeuralNetworkWaveFunction
from deepqmc import Molecule
from deepqmc import MolecularHamiltonian
from deepqmc.sampling import chain, MetropolisSampler, DecorrSampler
from deepqmc import train

#define molecule and molecular hamiltonian
mol = Molecule.from_name('LiH')
H = MolecularHamiltonian(mol=mol)

#read configuration file
deepqmc_dir = os.path.dirname(deepqmc.__file__)
config_dir = os.path.join(deepqmc_dir, 'conf/ansatz')


with initialize_config_dir(version_base=None, config_dir=config_dir):
    cfg = compose(config_name='default')

_ansatz = instantiate(cfg, _recursive_=True, _convert_='all')

ansatz = instantiate_ansatz(H, _ansatz)


sampler = chain(DecorrSampler(length=20),MetropolisSampler(H))

train(H, ansatz, 'kfac', sampler, steps=1000, electron_batch_size=2000, seed=42, workdir='runs/01')`


This is what I get in the terminal:


An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

equilibrate sampler:   6%|██████▉                                                                                                        | 62/1000 [02:13<33:33,  2.15s/it, tau=0.262]
training:   0%|                                                                                                                                              | 0/1000 [00:00<?, ?it/s]2024-08-27 16:02:55.285908: E external/xla/xla/service/slow_operation_alarm.cc:65] 
********************************
[Compiling module pmap__step] Very slow compile? If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
2024-08-27 16:04:17.656937: E external/xla/xla/service/slow_operation_alarm.cc:133] The operation took 3m22.374570448s

********************************
[Compiling module pmap__step] Very slow compile? If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
training:  33%|███████████████████████████████████████▎                                                                              | 333/1000 [44:44<1:29:36,  8.06s/it, E=nan(nan)]
WARNING:deepqmc.train:Restarting due to a NaN...
training:  33%|███████████████████████████████████████▎                                                                              | 333/1000 [34:40<1:09:26,  6.25s/it, E=nan(nan)]
WARNING:deepqmc.train:Restarting due to a NaN...
training:   6%|███████                                                                                                                | 59/1000 [13:20<2:14:41,  8.59s/it, E=nan(nan)]


Note the recurrent error: "WARNING:deepqmc.train:Restarting due to a NaN..."

I have no clue what could be the problem. This is the code provided in the tutorial. Could it have to do with me not having CUDA configured (not having access to a NVIDIA card.
