### ISSUE TITLE
Starting with deepqmc

### ISSUE THREAD

**Issue by Aqsa-physics** [deepqmc/deepqmc#218]
Hello guys,
I have just installed Deepqmc and now trying to run simple example code to understand it better. I found this example code online,
`
from deepqmc.molecule import Molecule
from deepqmc import evaluate, train
from deepqmc.wf import PauliNet

mol = Molecule.from_name('LiH')
net = PauliNet.from_hf(mol).cuda()
train(net)
evaluate(net)
`

while running it I get the following error,
**cannot import name 'evaluate' from 'deepqmc'**

I think I need to change the import function, but i am unable to find enough examples for the available deepqmc libraries and how to use them. Is there a place where they are listed?
I want to write my own code from scratch or built upon an example to get clearer understanding.

I installed deepqmc on my mac through git repository

**Comment by zenoone** [comment]
Hi,
welcome to DeepQMC!

The code you are sharing appears to be a very old snippet from a preceding torch implementation. To get started with the current version of DeepQMC I would recommend to follow the [tutorial](https://deepqmc.github.io/tutorial.html). This will give you a basic understanding of the main parts of the code and how to read the logs of training and evaluation. For running actual calculations, the [command line interface](https://deepqmc.github.io/cli.html) is the most convenient way. 

If you run into any issues following the tutorial or you are interested in further details feel free to get back to us.

**Comment by zenoone** [comment]
I am closing this issue as solved for now. Feel free to open a new issue, if you have any questions or suggestions about getting started with DeepQMC.
