### ISSUE TITLE
Utilize multiple processes and GPUs

### ISSUE THREAD

**Issue by n-gao** [deepqmc/deepqmc#22]
## Problem
Training PauliNet does not utilze the GPU well. I ran the following code on a machine with 8 cores, 188GB RAM and 4 V100s:
```python
from deepqmc import Molecule, evaluate, train
from deepqmc.wf import PauliNet

mol = Molecule.from_name('Be')
net = PauliNet.from_hf(mol).cuda()
train(net)
evaluate(net)
```

The code only utilizes as single core and a single GPU. That one core bottlenecks the GPU usage heavily (100% on that one core), during sampling the GPU is used to about ~30% and during training it varies between 0 and 60%.

There is a lot of performance left on the table especially if running a task takes multiple hours.

## Solution
It would be great if the code could use multiple processes and GPUs to split the load evenly and improve performance, e.g., having 1-4 processes per GPU could take advantage of the unused compute capabilities.

**Comment by jhrmnn** [comment]
Interesting observations. We've done all calculations on a single GTX 1080 Ti, and I've tested the code a bit on Titan RTX, I think V100 is more powerful. I can only say that we haven't really looked into optimization much yet. If you can identify the source of the problem and fix it, I'll be happy to accept a PR.

As for multiple GPUs, I haven't had that use case in mind. I'd rather think that one would run multiple different systems in parallel, each on a single GPU. After all, the systems we've tried are all still relatively small. But again, I'd be happy to accept a PR that introduces the possibility to train a single model across multiple GPUs.

**Comment by n-gao** [comment]
As training a single system requires multiple hour, I see its advantageous to be able to finish such a job faster. 

On another performance note:
I just noticed that if matplotlib is installed the performance of evaluating is *very* bad. One equilibrating step during evaluation jumps from 0.2s to about 90s. If it is matplotlib is not installed it warns me to install matplotlib.

**Comment by jhrmnn** [comment]
Damn. I think what happens is that all these problems just get manifestly obvious with your much faster GPU. When I look at this with 1080, the difference between generating and not generating the figures isn't too big. I guess if I looked at it on a larger system than Be atom, the difference might be negligible. When I look at it with Titan, the difference is already obvious (4-fold just for sampling, 2-fold when also evaluating energy). Also, it's possible I've only tested the performance hit of the matplotlib figures in the context of training, where it's even less important.

Anyway, I'm just explaining why this probably happened, clearly this is unacceptable. Please, also bear in mind that although the package and code might look nice and polished, this is still very much a research code :)

Anyway, I will make the figure generation optional, off by default.

**Comment by n-gao** [comment]
Thank you for the response! I understand that research code is not highly optimized. Though, the creation of two histograms should not take 90s? Can you think of something that causes this?

**Comment by jhrmnn** [comment]
Wait, you mean that a single equilibration step takes 90 s? I thought you meant the whole equilibration. Then something else must be wrong. I just ran evaluation of PauliNet with all default parameters for Be atom, and even with the figures, it's roughly 1 step per s. Without figures, it was 4 steps per s.

**Comment by n-gao** [comment]
Sorry, this seems to be related to our workstation and not to your code.

**Comment by MrRobot2211** [comment]
Hi I am working on a parrallelization hot-fix. I will open a PR soon unless there are anynews here.
