### ISSUE TITLE
PauliNet initialization

### ISSUE THREAD

**Issue by n-gao** [deepqmc/deepqmc#28]
Hi,

if I understand PauliNet correctly, it is fine tuning the HF results by using a deep neural network (the equivariant interaction block + backflow network + jastrow network). From running PauliNet, I learned that it start off at the HF-level performance. 
Some questions arise from that:
* Does that mean the Backflow network is initialized such its output is 0 (if added) or 1 (if multiplied) or what initialization technique is used? 
* Is HF performed at every iteration? Isn't that a potential bottleneck?
* What do you think about fine-tuning HF instead of using HF for pretraining like in FermiNet[1]? Doesn't pre-training improve the starting point for the rest of the parameters (as these are not randomly initialized but already contain learned structure)? Also, there is no need to query PySCF after the pretraining?

Thank you for you response!

[1] Pfau, David, et al. "Ab-Initio Solution of the Many-Electron Schr\" odinger Equation with Deep Neural Networks." arXiv preprint arXiv:1909.02487 (2019).

**Comment by jhrmnn** [comment]
> * Does that mean the Backflow network is initialized such its output is 0 (if added) or 1 (if multiplied) or what initialization technique is used?

All the networks are initialized in the default Pytorch way, but the scales in the architecture are such, that these default initialization don't perturb the HF baseline too much.

> * Is HF performed at every iteration? Isn't that a potential bottleneck?

No, it's not. The HF equations are solved only in the beginning to initialize the baseline HF wave function.

> * What do you think about fine-tuning HF instead of using HF for pretraining like in FermiNet[1]? Doesn't pre-training improve the starting point for the rest of the parameters (as these are not randomly initialized but already contain learned structure)? Also, there is no need to query PySCF after the pretraining?

We haven't tested that approach, so I can't really say. As I say above, we query PySCF only at initialization, not afterwards.

**Comment by maxiwelian** [comment]
Could you expand on the usage of pyscf. My understanding is the HF orbitals are functions dependent on r. Are you saying the call to PySCF generates those functions, and after that initial call you have the functions? 

I say this because the HF orbitals will change as walkers move.

**Comment by jhrmnn** [comment]
The HF orbitals are functions dependent on r. The call to PySCF is needed to solve the HF equations, that is, to determine those functions. Those are then fixed throughout the optimizations. The walkers move, so the inputs to those orbital functions change, and so the outputs (and this is evaluated at each step), but the functions themselves remain the same.
