### ISSUE TITLE
Pip Installation Error: No matching distribution found for deepqmc

### ISSUE THREAD

**Issue by sayan1999** [deepqmc/deepqmc#31]
I am using python-3.8.5 on ubuntu 20.04. 

An attempt to install the package with
```
pip install -U deepqmc
```

gives following error:
```
ERROR: Could not find a version that satisfies the requirement deepqmc (from versions: none)
ERROR: No matching distribution found for deepqmc
```

**Comment by jhrmnn** [comment]
That's weird. Are you certain the Pip used is from the 3.8.5 Python distribution? You would get a similar error if you tried to install Deepqmc in Python 3.6 or lower.

**Comment by sayan1999** [comment]
Okay Okay, that's what happened then, seems like, I created an enviroment in conda without it's own python, but using system's root python binaries, so pip also defaulted to system's. Thanks for pointing it out. It's resolved now.
