### ISSUE TITLE
Google Colab installation issue

### ISSUE THREAD

**Issue by RodolfoFerro** [deepqmc/deepqmc#32]
Hello! 

I'm facing an error when trying to install the package in Google Colab. 
I've noticed that Colab uses Python 3.6.9 so I installed Python 3.7 but the problem persists as you can see here: https://colab.research.google.com/drive/1NjGkqTxDo_eud4DLFixDWl656e10JfOa?usp=sharing

Any help is appreciated.
Thanks in advance.

**Comment by jhrmnn** [comment]
Hi, thanks for the interest. I'm not familiar with Google Colab, and using a different Python version than the provided one seems nontrivial, so I'm unable to help, sorry. If you figure it out, I'll be happy to merge a PR that includes the notebook in the README.
