### ISSUE TITLE
Hardware requirement GPU from NAVIDA 

### ISSUE THREAD

**Issue by Int-Soft** [deepqmc/deepqmc#33]
![NAVIDIA](https://user-images.githubusercontent.com/72168470/108586371-05b88c00-735f-11eb-9ec9-96d45f3307e2.png)

Is it possible to use MPI in this library? I think it is based on Pyscf and there is an MPI version https://github.com/pyscf/mpi4pyscf

Can I use in https://deepqmc.github.io/tutorial.html
from deepqmc.wf import PauliNet
net = PauliNet.from_hf(mol, cas=(2, 4)).cuda()

instead of cuda() mpi()
or I must port the library to mpipyscf myself?

**Comment by jhrmnn** [comment]
CUDA and MPI serve entirely different purposes. CUDA is for running code on a GPU, MPI is for parallelization across multiple machines.

PySCF is used only as a baseline here, its contribution to the total computational cost is negligible, so there is no reason to use it with MPI.

**Comment by Int-Soft** [comment]
Thus, the answer is that deepqmc runs only using cuda() as in this line
PauliNet.from_hf(mol, cas=(2, 4)).cuda()

I cannot parallelize the code when I run it on CPU, even thought using PyTorch distributor  other than CUDA 
https://pytorch.org/docs/stable/distributed.html#backends-that-come-with-pytorch

**Comment by jhrmnn** [comment]
The choice of a device (CPU/CUDA) is orthogonal to the choice of the `torch.distributed` backend. DeepQMC currently doesn't support `torch.distributed`. If it did, it wouldn't be a replacement for CUDA, but an additional functionality that could be used with CUDA in principle, and its use wouldn't be as easy as calling `.cuda()` on the model.

**Comment by Int-Soft** [comment]
That's mean, I can only run the model on GPU, instances like https://docs.aws.amazon.com/dlami/latest/devguide/gpu.html
and cannot be run on HPC that uses mix GPUs and CPUs with InfiniBand networking.

**Comment by jhrmnn** [comment]
You run it on a single node in an HPC cluster, requesting a single GPU. That's what I do regularly.
