### ISSUE TITLE
PauliNet class function name "pop_chargse"

### ISSUE THREAD

**Issue by husisy** [deepqmc/deepqmc#36]
curiously, in deepqmc/wf/paulinet/paulinet.py/line326, is the function name "pop_chargse" a typo? [link](https://github.com/deepqmc/deepqmc/blob/master/src/deepqmc/wf/paulinet/paulinet.py#L326)

**Comment by jhrmnn** [comment]
Indeed! Thanks for reporting. We didn't notice before, because the inherited `pop_charges` kicked in, which does an ok-enough job, and this part of the code doesn't really affect the performance in a meaningful way.
