### ISSUE TITLE
Tensorboard not working as shown in tutorial

### ISSUE THREAD

**Issue by MrRobot2211** [deepqmc/deepqmc#40]
Hi I am following the tutorial from the official page, i have created a `runs` folder in the same directory, but nothing seems to get stored there when running training.

**Comment by jhrmnn** [comment]
Thanks for catching all these bugs in the tutorial! And sorry about them. The tutorial didn't say that `train()` needs to be called with an optional `workdir` argument. It's fixed now.

https://deepqmc.github.io/tutorial.html#optimize-the-ansatz
