### ISSUE TITLE
Stale `psi` values in sampler

### ISSUE THREAD

**Issue by ae-foster** [deepqmc/deepqmc#77]
This issue is closely related to #72 .

The `psi` values of a sampler state are set when that point is first proposed. This causes problems if the wavefunction is subsequently updated by a gradient step. Now the old `psi` values do not correspond to the correct density, and hence can lead to problematic sampling. In severe cases, this can allow points with a current `psi` value very close to 0 being sampled and causing crashes when the wavefunction is updated.

I was able to fix this issue for the `MetropolisSampler` sampler by simply adding the line

    state = self._update(state, wf)

as the first line of this method https://github.com/deepqmc/deepqmc/blob/299f4c4a47cb9a55a8d12c870f5b2168bb5f35e1/src/deepqmc/sampling.py#L87

However, this is not optimal as it may query the wavefunction more frequently than strictly necessary (e.g. when used inside a decorrelation sampler)

**Comment by zenoone** [comment]
This is a correct observation. The `psi` values have to be updated between the sampling and the optimization step, which is currently not the case (I think this got lost in a somewhat recent refactor). Thanks for spotting, I will come up with a general solution.
